Repository ComplianceAsCode/compliance-operator, pull requests merged in 2022-09, with the labels that each got.

#78 Added the ability to check default KubeletConfig
  CHANGELOG.md
  cmd/manager/aggregator.go
  cmd/manager/api-resource-collector.go
  cmd/manager/log.go
  cmd/manager/resultcollector.go
  cmd/manager/resultserver.go
  cmd/manager/resultserver_test.go
  cmd/manager/scap.go
  cmd/manager/scap_test.go
  config/rbac/api_resource_collector_cluster_role.yaml
  go.mod
  go.sum
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/utils/compare_json.go
  pkg/utils/nodeutils.go
  pkg/utils/parse_arf_result.go
  tests/e2e/e2e_test.go
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/logo.png
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/github.com/wI2L/jsondiff/.codecov.yml
  vendor/github.com/wI2L/jsondiff/.gitignore
  vendor/github.com/wI2L/jsondiff/.golangci.yaml
  vendor/github.com/wI2L/jsondiff/.goreleaser.yml
  vendor/github.com/wI2L/jsondiff/CHANGELOG.md
  vendor/github.com/wI2L/jsondiff/LICENSE
  vendor/github.com/wI2L/jsondiff/README.md
  vendor/github.com/wI2L/jsondiff/compare.go
  vendor/github.com/wI2L/jsondiff/differ.go
  vendor/github.com/wI2L/jsondiff/equal.go
  vendor/github.com/wI2L/jsondiff/hash.go
  vendor/github.com/wI2L/jsondiff/operation.go
  vendor/github.com/wI2L/jsondiff/option.go
  vendor/github.com/wI2L/jsondiff/pointer.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#91 Refactor helm installs
  config/helm/templates/api_resource_collector_cluster_role.yaml
  config/helm/templates/api_resource_collector_cluster_role_binding.yaml
  config/helm/templates/api_resource_collector_role.yaml
  config/helm/templates/api_resource_collector_role_binding.yaml
  config/helm/templates/complianceremediation_editor_role.yaml
  config/helm/templates/complianceremediation_viewer_role.yaml
  config/helm/templates/compliancescan_editor_role.yaml
  config/helm/templates/compliancescan_viewer_role.yaml
  config/helm/templates/compliancesuite_editor_role.yaml
  config/helm/templates/compliancesuite_viewer_role.yaml
  config/helm/templates/leader_election_role.yaml
  config/helm/templates/leader_election_role_binding.yaml
  config/helm/templates/metrics_cluster_role.yaml
  config/helm/templates/metrics_role_binding.yaml
  config/helm/templates/operator_cluster_role.yaml
  config/helm/templates/operator_cluster_role_binding.yaml
  config/helm/templates/operator_role.yaml
  config/helm/templates/operator_role_binding.yaml
  config/helm/templates/profilebundle_editor_role.yaml
  config/helm/templates/profilebundle_viewer_role.yaml
  config/helm/templates/profileparser_role.yaml
  config/helm/templates/profileparser_role_binding.yaml
  config/helm/templates/remediation_aggregator_cluster_role.yaml
  config/helm/templates/remediation_aggregator_cluster_role_binding.yaml
  config/helm/templates/remediation_aggregator_role.yaml
  config/helm/templates/remediation_aggregator_role_binding.yaml
  config/helm/templates/rerunner_role.yaml
  config/helm/templates/rerunner_role_binding.yaml
  config/helm/templates/resultscollector_role.yaml
  config/helm/templates/resultscollector_role_binding.yaml
  config/helm/templates/resultserver_role.yaml
  config/helm/templates/resultserver_role_binding.yaml
  config/helm/templates/role.yaml
  config/helm/templates/role_binding.yaml
  config/helm/templates/scansettingbinding_editor_role.yaml
  config/helm/templates/scansettingbinding_viewer_role.yaml
  config/helm/templates/tailoredprofile_editor_role.yaml
  config/helm/templates/tailoredprofile_viewer_role.yaml
  doc/install.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#93 Add a release note for Operator SDK bump
  CHANGELOG.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#103 images: Don't enable an obsolete copr repo
  images/openscap/Dockerfile
  images/openscap/Dockerfile.ci
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#109 Use ghcr.io content image as default
  Makefile
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  config/manager/deployment.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#94 bug 2092913: scan: Delete scan pods when deleting the scan itself and debug: true
  CHANGELOG.md
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
Labels: approved, lgtm, bugzilla/severity-medium, bugzilla/valid-bug, qe-approved, docs-approved

#114 Makefile: Set IMG during image-to-cluster
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#121 Makefile: fix catalog img variable
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#118 Allow running a subset of tests through a MakeFile variable
  Makefile
  tests/e2e/framework/context.go
  tests/e2e/framework/framework.go
  tests/e2e/helpers.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#120 Makefile: Fix release-images target prereqs
  Makefile
  doc/contributor.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#119 OCPBUGS-379: scan: Add conditions to scans
  CHANGELOG.md
  config/crd/bases/compliance.openshift.io_compliancescans.yaml
  config/crd/bases/compliance.openshift.io_compliancesuites.yaml
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/apis/compliance/v1alpha1/conditions.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, docs-approved, jira/severity-critical, jira/valid-bug

#123 Fix -testType option for e2e
  tests/e2e/framework/framework.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#125 Release v0.1.54
  CHANGELOG.md
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  bundle/manifests/compliance.openshift.io_compliancescans.yaml
  bundle/manifests/compliance.openshift.io_compliancesuites.yaml
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#45 Add container and repository security scanning
  .github/workflows/container-scan-trivy.yml
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#127 Reproducible builds: Ensure we can get reproducible builds for CO
  Makefile
Labels: approved, lgtm

#128 Update to golang 1.18
  Dockerfile.ci
  Dockerfile.ocp
  build/Dockerfile
  go.mod
  go.sum
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#85 Make scanner's and api-resource-collector's limits configurable
  CHANGELOG.md
  config/crd/bases/compliance.openshift.io_compliancescans.yaml
  config/crd/bases/compliance.openshift.io_compliancesuites.yaml
  config/crd/bases/compliance.openshift.io_scansettings.yaml
  config/helm/crds/compliance.openshift.io_compliancescans_crd.yaml
  config/helm/crds/compliance.openshift.io_compliancesuites_crd.yaml
  config/helm/crds/compliance.openshift.io_scansettings_crd.yaml
  doc/crds.md
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/compliancescan/scan.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#130 Resultserver rotation test timing
  cmd/manager/resultserver_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#124 Add upstream doc for KubeletConfig usage
  CHANGELOG.md
  doc/usage.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#132 Release v0.1.55
  CHANGELOG.md
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  bundle/manifests/compliance.openshift.io_compliancescans.yaml
  bundle/manifests/compliance.openshift.io_compliancesuites.yaml
  bundle/manifests/compliance.openshift.io_scansettings.yaml
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#133 Move limit release note to correct release.
  CHANGELOG.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#134 Makefile: Push latest tag for all release images
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#136 Update content image in bundle samples
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  config/samples/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
  config/samples/compliance.openshift.io_v1alpha1_profilebundle_cr.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#135 Update usage doc
  CHANGELOG.md
  doc/usage.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#141 Fix deployment on OCP 4.6
  cmd/manager/operator.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#143 bug 2098581: Don't import batchv1beta1 anymore
  CHANGELOG.md
  pkg/controller/compliancesuite/suitererunner.go
  tests/e2e/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, bugzilla/severity-low

#146 Makefile: Fix kustomize install for go1.18
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#148 Release v0.1.56
  CHANGELOG.md
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#151 Add a script to conditionally set upstream remote
  CHANGELOG.md
  Makefile
  utils/git-remote.sh
Labels: approved, lgtm, qe-approved, px-approved, docs-approved
