Repository ComplianceAsCode/compliance-operator, pull requests merged in 2022-05, with the labels that each got.

#10 Modify api-resource collector permission
  CHANGELOG.md
  deploy/role.yaml
Labels: approved, lgtm

#9 Release v0.1.50
  CHANGELOG.md
  deploy/compliance-operator-chart/Chart.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved

#15 Bug 2082151: Fix scanner pod script mount permission
  CHANGELOG.md
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm, bugzilla/severity-medium, bugzilla/valid-bug

#12 Add manualRules to tailoredProfile CRD
  CHANGELOG.md
  cmd/manager/aggregator.go
  deploy/compliance-operator-chart/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
  deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
  deploy/role.yaml
  doc/crds.md
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/controller/tailoredprofile/tailoredprofile_controller_test.go
  pkg/profileparser/profileparser_suite_test.go
  pkg/utils/nameutils.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
  pkg/xccdf/tailoring.go
  tests/e2e/e2e_test.go
Labels: approved

#14 Add CodeQL analysis job
  .github/workflows/codeql-analysis.yml
  cmd/manager/resultserver.go
  pkg/profileparser/profileparser.go
Labels: approved, lgtm

#16 Fix a minor spelling issue in CHANGELOG.md
  CHANGELOG.md
Labels: approved, lgtm

#17 Release v0.1.51
  CHANGELOG.md
  deploy/compliance-operator-chart/Chart.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_tailoredprofiles_crd.yaml
  version/version.go
Labels: approved, lgtm

#36 Bug 2082431: Fix MachineConfig base64 encoding issue on OVN cluster
  CHANGELOG.md
  pkg/controller/compliancesuite/compliancesuite_controller_test.go
  pkg/utils/nodeutils.go
Labels: approved, lgtm, bugzilla/invalid-bug, bugzilla/severity-high

#39 Release v0.1.52
  CHANGELOG.md
  deploy/compliance-operator-chart/Chart.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm

#38 Bug 2088202: Adjust the namespace for the restricted Pod Security Admission
  CHANGELOG.md
  deploy/ns.yaml
  deploy/operator.yaml
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/profilebundle/profilebundle_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
