Repository ComplianceAsCode/compliance-operator, pull requests merged in 2022-07, with the labels that each got.

#50 Add Priority Class Proposal
  doc/priorityClass.md
Labels: approved, lgtm

#53 doc/crds.md: Use description in the TP example
  doc/crds.md
Labels: approved, lgtm

#64 Add an enhancements template
  CHANGELOG.md
  enhancements/README.md
  enhancements/template.md
Labels: approved, lgtm

#58 BUG 2102511: Fix hardcoded logic by filtering to expected file name.
  pkg/utils/nodeutils.go
  pkg/utils/nodeutils_test.go
Labels: approved, lgtm, bugzilla/invalid-bug, ok-to-test, bugzilla/severity-high

#70 Bug 2060726: Use namespace when creating ServiceMonitor
  cmd/manager/operator.go
  cmd/manager/operator_test.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#72 trivial: fix minor grammatical issue in contrib docs
  doc/contributor.md
Labels: approved, lgtm

#68 Added changelog for fixing KubeletConfig issue
  CHANGELOG.md
Labels: approved, lgtm
