Repository ComplianceAsCode/compliance-operator, pull requests merged in 2022-08, with the labels that each got.

#74 Update xmlquery dependency
  go.mod
  go.sum
  vendor/github.com/antchfx/xmlquery/README.md
  vendor/github.com/antchfx/xmlquery/go.mod
  vendor/github.com/antchfx/xmlquery/go.sum
  vendor/github.com/antchfx/xmlquery/node.go
  vendor/github.com/antchfx/xmlquery/parse.go
  vendor/github.com/antchfx/xmlquery/query.go
  vendor/github.com/antchfx/xpath/README.md
  vendor/github.com/antchfx/xpath/build.go
  vendor/github.com/antchfx/xpath/func.go
  vendor/github.com/antchfx/xpath/func_go110.go
  vendor/github.com/antchfx/xpath/operator.go
  vendor/github.com/antchfx/xpath/parse.go
  vendor/github.com/antchfx/xpath/query.go
  vendor/golang.org/x/net/http2/README
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/errors.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_random.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/punycode.go
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_other.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: approved, lgtm

#71 Add PriorityClass
  CHANGELOG.md
  deploy/compliance-operator-chart/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/compliance-operator-chart/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/compliance-operator-chart/crds/compliance.openshift.io_scansettings_crd.yaml
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/crds/compliance.openshift.io_scansettings_crd.yaml
  deploy/role.yaml
  doc/crds.md
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancescan/scantype.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/suitererunner.go
  pkg/utils/podutils.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, qe-approved, docs-approved

#81 Bug 2117268: api-resource-collector: Don't attempt to parse empty Ignition
  CHANGELOG.md
  cmd/manager/scap.go
  cmd/manager/scap_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved, px-approved, docs-approved

#82 operator: Override WATCH_NAMESPACE="" to WATCH_NAMESPACE=openshift-compliance
  CHANGELOG.md
  cmd/manager/operator.go
  pkg/controller/common/constants.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#76 Add upstream doc for PriorityClass
  doc/usage.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#84 doc: Document how to increase operator's memory limits
  doc/usage.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#67 Added KubeletConfig default configuration checks proposal
  enhancements/improve-kubeletconfig-default-configuration-check-enhancement.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#92 Ignore tests/_setup directory
  .gitignore
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#57 Use an absolute reference for the release remote
  CHANGELOG.md
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved
