Repository ComplianceAsCode/compliance-operator, pull requests merged in 2022-10, with the labels that each got.

#149 Use ISO 8601 time format for logs
  cmd/manager/operator.go
  cmd/manager/operator_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#153 OCPBUGS-2156: suite: Fall back to using betav1 cronjob if v1 cronjob is not available
  CHANGELOG.md
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/suitererunner.go
  pkg/controller/compliancesuite/suitererunner_cron_compat.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, px-approved, docs-approved, jira/severity-critical, jira/valid-bug

#157 Fix Makefile Generate section
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#158 Use tab indentation for `make help`
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#161 Update Release section in Makefile
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#166 update the golang.org/x/text dependency to v0.3.8
  go.mod
  go.sum
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/text/width/tables10.0.0.go
  vendor/golang.org/x/text/width/tables11.0.0.go
  vendor/golang.org/x/text/width/tables12.0.0.go
  vendor/golang.org/x/text/width/tables13.0.0.go
  vendor/golang.org/x/text/width/tables9.0.0.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#162 Stash e2e test output when running locally
  .gitignore
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#168 Update change log to include Makefile updates
  CHANGELOG.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#170 Cleanup openscap images tag and dockerfile
  Makefile
  images/openscap/Dockerfile.maint-1.3
  images/openscap/mrogers-openscap-with-yaml-epel-8.repo
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#167 make: Build a file-based catalog
  CHANGELOG.md
  Makefile
  catalog/preamble.json
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#169 Release v0.1.57
  CHANGELOG.md
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm

#172 openscap: Update libksba manually to make CVE scanners happy
  images/openscap/Dockerfile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved
