Repository ComplianceAsCode/compliance-operator, pull requests merged in 2023-10, with the labels that each got.

#428 Fix minor spelling mistakes in contributor documentation
  doc/contributor.md
Labels: approved, lgtm

#403 Workshop: Add new section for common rules
  doc/tutorials/workshop/content/exercises/09-writing-rules.md
  doc/tutorials/workshop/content/exercises/10-rule-parametrization.md
  doc/tutorials/workshop/content/exercises/11-node-rules.md
  doc/tutorials/workshop/content/exercises/12-common-rules.md
Labels: approved, lgtm

#382 Document namespace prefix when scanning a hosted cluster
  doc/usage.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#418 Remove ginkgo v2 dependency
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#396 CMP-2132: Implement suspend and resume scan schedule
  CHANGELOG.md
  config/crd/bases/compliance.openshift.io_compliancecheckresults.yaml
  config/crd/bases/compliance.openshift.io_complianceremediations.yaml
  config/crd/bases/compliance.openshift.io_compliancescans.yaml
  config/crd/bases/compliance.openshift.io_compliancesuites.yaml
  config/crd/bases/compliance.openshift.io_profilebundles.yaml
  config/crd/bases/compliance.openshift.io_profiles.yaml
  config/crd/bases/compliance.openshift.io_rules.yaml
  config/crd/bases/compliance.openshift.io_scansettingbindings.yaml
  config/crd/bases/compliance.openshift.io_scansettings.yaml
  config/crd/bases/compliance.openshift.io_tailoredprofiles.yaml
  config/crd/bases/compliance.openshift.io_variables.yaml
  doc/usage.md
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/apis/compliance/v1alpha1/scansettingbinding_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/compliancesuite/suitererunner_cron_compat.go
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
  tests/e2e/framework/common.go
  tests/e2e/serial/main_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#375 Add enhancement for suspending and resuming scan schedules
  enhancements/suspend-and-resume-scan-schedule.md
Labels: approved, lgtm, qe-approved, docs-approved

#431 Extend workshop with a section about `jq` filters
  doc/tutorials/workshop/content/exercises/09-writing-rules.md
  doc/tutorials/workshop/content/exercises/10-rule-parametrization.md
  doc/tutorials/workshop/content/exercises/11-node-rules.md
  doc/tutorials/workshop/content/exercises/12-common-rules.md
  doc/tutorials/workshop/content/exercises/13-complex-yaml.md
  doc/tutorials/workshop/content/exercises/images/jqfilter_preprocessing.png
Labels: approved, lgtm

#389 Docs: Fix URI for must-gather image
  doc/usage.md
Labels: approved, lgtm, qe-approved

#446 Correct "ScanSettings" typo
  doc/usage.md
Labels: approved, lgtm, ok-to-test

#448 Use golang 1.20
  Dockerfile.ci
  Dockerfile.ocp
Labels: approved, lgtm, qe-approved

#395 [Enhancements]: Add Profile Name in Rule
  enhancements/profile-name-in-rule.md
Labels: approved, lgtm, qe-approved

#451 Add an integration test to verify HTTP version usage
  tests/e2e/framework/utils.go
  tests/e2e/parallel/main_test.go
Labels: approved, lgtm

#456 Build the operator for FIPS enabled environments
  cmd/manager/fips.go
Labels: approved, lgtm

#460 Minor workshop fixes
  doc/tutorials/workshop/content/exercises/02-installation.md
  doc/tutorials/workshop/content/exercises/11-node-rules.md
  doc/tutorials/workshop/content/exercises/13-complex-yaml.md
Labels: approved, lgtm
