Repository ComplianceAsCode/compliance-operator, pull requests merged in 2023-06, with the labels that each got.

#332 Add ability to deploy CO on Hosted Cluster through OLM
  CHANGELOG.md
  Makefile
  config/catalog/subscription-hypershift.yaml
  doc/usage.md
Labels: approved, lgtm, do-not-merge/hold, px-approved, docs-approved

#336 OCPBUGS-7456 Fix valuesUsed rendering
  CHANGELOG.md
  pkg/profileparser/profileparser.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
Labels: approved, lgtm, do-not-merge/hold

#331 Fetch CO deployment object for Platform CPE
  CHANGELOG.md
  cmd/manager/api-resource-collector.go
  cmd/manager/operator.go
  cmd/manager/scap.go
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#346 OLM: Provide an OCP-specific bundle kustomize
  Makefile
  config/openshift-bundle/kustomization.yaml
  config/openshift-bundle/manager_patch.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#323 Add Start and End time to CRD
  CHANGELOG.md
  config/crd/bases/compliance.openshift.io_compliancescans.yaml
  config/crd/bases/compliance.openshift.io_compliancesuites.yaml
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#354 Update ocp branch references
  Makefile
  doc/contributor.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#110 Implement result and remediation forwarding
  cmd/manager/aggregator.go
  pkg/controller/compliancescan/forwarder.go
  pkg/controller/compliancescan/forwarder_test.go
Labels: approved, lgtm, px-approved, docs-approved
