Repository ComplianceAsCode/compliance-operator, pull requests merged in 2023-11, with the labels that each got.

#457 Implement build flags
  Makefile
Labels: approved, lgtm

#383 Propose enhancement for versioning profiles
  enhancements/profile-versioning.md
Labels: approved, lgtm, qe-approved, docs-approved

#425 CMP-2130: Implement support for profile versioning
  CHANGELOG.md
  bundle/manifests/compliance.openshift.io_compliancecheckresults.yaml
  bundle/manifests/compliance.openshift.io_complianceremediations.yaml
  bundle/manifests/compliance.openshift.io_compliancescans.yaml
  bundle/manifests/compliance.openshift.io_compliancesuites.yaml
  bundle/manifests/compliance.openshift.io_profilebundles.yaml
  bundle/manifests/compliance.openshift.io_profiles.yaml
  bundle/manifests/compliance.openshift.io_rules.yaml
  bundle/manifests/compliance.openshift.io_scansettingbindings.yaml
  bundle/manifests/compliance.openshift.io_scansettings.yaml
  bundle/manifests/compliance.openshift.io_tailoredprofiles.yaml
  bundle/manifests/compliance.openshift.io_variables.yaml
  config/crd/bases/compliance.openshift.io_profiles.yaml
  pkg/apis/compliance/v1alpha1/profile_types.go
  pkg/profileparser/profileparser.go
  tests/e2e/parallel/main_test.go
Labels: approved, lgtm, qe-approved, docs-approved, jira/valid-reference

#430 Harden the deployment and the profilebundle
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  config/manager/deployment.yaml
  pkg/controller/profilebundle/profilebundle_controller.go
Labels: approved, lgtm, qe-approved

#466 update link to oc compliance plugin
  doc/tutorials/workshop/content/exercises/03-creating-your-first-scan.md
  doc/tutorials/workshop/content/exercises/06-troubleshooting.md
Labels: approved, lgtm, ok-to-test, qe-approved, px-approved, docs-approved

#468 fix link
  doc/tutorials/workshop/content/exercises/03-creating-your-first-scan.md
Labels: approved, lgtm, ok-to-test, qe-approved, px-approved, docs-approved

#398 Add Profile Name to rule
  pkg/apis/compliance/v1alpha1/rule_types.go
  pkg/profileparser/profileparser.go
  pkg/utils/parse_arf_result.go
  tests/e2e/framework/common.go
  tests/e2e/parallel/main_test.go
Labels: approved, lgtm, qe-approved, px-approved

#221 OCPBUGS-3009: Prune stale CCRs before aggregating scan results
  CHANGELOG.md
  cmd/manager/aggregator.go
  config/rbac/remediation_aggregator_role.yaml
  tests/e2e/framework/common.go
  tests/e2e/parallel/main_test.go
  tests/e2e/serial/main_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#485 CMP-3009: Update manifest to include new aggregator permissions
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#486 Fix dpanic during remediation logging
  pkg/controller/compliancescan/forwarder.go
Labels: approved, lgtm
