Repository ComplianceAsCode/compliance-operator, pull requests merged in 2023-02, with the labels that each got.

#208 Fix e2e flaky issue
  tests/e2e/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug

#69 Add enhancement proposal for result forwarding
  enhancements/results-forwarding.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#207 Update RBAC to allow remediations that set projects templates
  config/rbac/operator_cluster_role.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#206 OCPBUGS-6710: remediations: Normalize remediations' annotations to avoid needlesly marking remediations as Outdated
  CHANGELOG.md
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types_test.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, px-approved, jira/valid-bug, jira/valid-reference

#215 Minor follow-ups to code review of PR 206
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#195 OCPBUGS-6827: ssb: Presume Platform scan if no scan type is given with annotations
  CHANGELOG.md
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/valid-reference

#217 Release v0.1.61
  CHANGELOG.md
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  bundle/manifests/compliance.openshift.io_compliancecheckresults.yaml
  bundle/manifests/compliance.openshift.io_complianceremediations.yaml
  bundle/manifests/compliance.openshift.io_compliancescans.yaml
  bundle/manifests/compliance.openshift.io_compliancesuites.yaml
  bundle/manifests/compliance.openshift.io_profilebundles.yaml
  bundle/manifests/compliance.openshift.io_profiles.yaml
  bundle/manifests/compliance.openshift.io_rules.yaml
  bundle/manifests/compliance.openshift.io_scansettingbindings.yaml
  bundle/manifests/compliance.openshift.io_scansettings.yaml
  bundle/manifests/compliance.openshift.io_tailoredprofiles.yaml
  bundle/manifests/compliance.openshift.io_variables.yaml
  catalog/preamble.json
  config/crd/bases/compliance.openshift.io_compliancecheckresults.yaml
  config/crd/bases/compliance.openshift.io_complianceremediations.yaml
  config/crd/bases/compliance.openshift.io_compliancescans.yaml
  config/crd/bases/compliance.openshift.io_compliancesuites.yaml
  config/crd/bases/compliance.openshift.io_profilebundles.yaml
  config/crd/bases/compliance.openshift.io_profiles.yaml
  config/crd/bases/compliance.openshift.io_rules.yaml
  config/crd/bases/compliance.openshift.io_scansettingbindings.yaml
  config/crd/bases/compliance.openshift.io_scansettings.yaml
  config/crd/bases/compliance.openshift.io_tailoredprofiles.yaml
  config/crd/bases/compliance.openshift.io_variables.yaml
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#218 cleanup: Don't return from a utility function, return an error instead
  cmd/manager/resultcollector.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#225 Add Makefile target for generating unit test coverage reports
  Makefile
  doc/contributor.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#233 Add e2e help text to Makefile
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved
