Repository ComplianceAsCode/compliance-operator, pull requests merged in 2023-01, with the labels that each got.

#197 Fix e2e test
  tests/e2e/e2e_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#190 OCPBUGS-4621: Add non-nil check before comparing if KubeletConfig is fully rendered
  CHANGELOG.md
  pkg/utils/compare_json.go
  pkg/utils/nodeutils.go
  pkg/utils/nodeutils_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug

#187 OCPBUGS-4445: Excludes node sizing, and system reserved parameters from KubeletConfig rendering checks
  CHANGELOG.md
  pkg/utils/nodeutils.go
  pkg/utils/nodeutils_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, docs-approved, jira/valid-bug

#199 Use go 1.19
  Dockerfile.ci
  Dockerfile.ocp
  build/Dockerfile
  go.sum
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#188 OCPBUGS-4338: Apply all remediations associate with each ComplianceCheckResult
  CHANGELOG.md
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, px-approved, docs-approved, jira/valid-bug

#192 Add Timeout for scanner pod
  CHANGELOG.md
  config/crd/bases/compliance.openshift.io_compliancescans.yaml
  config/crd/bases/compliance.openshift.io_compliancesuites.yaml
  config/crd/bases/compliance.openshift.io_scansettings.yaml
  doc/usage.md
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/conditions.go
  pkg/controller/common/errors.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/scantype.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#202 Release v0.1.60
  CHANGELOG.md
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  bundle/manifests/compliance.openshift.io_compliancecheckresults.yaml
  bundle/manifests/compliance.openshift.io_compliancescans.yaml
  bundle/manifests/compliance.openshift.io_compliancesuites.yaml
  bundle/manifests/compliance.openshift.io_scansettings.yaml
  catalog/preamble.json
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved
