Repository ComplianceAsCode/compliance-operator, pull requests merged in 2023-03, with the labels that each got.

#236 Update e2e examples for running a single test
  Makefile
  doc/contributor.md
Labels: approved, lgtm, bugzilla/valid-bug

#241 renovate: Open PRs on weekends only, set labels
  renovate.json
Labels: approved, lgtm, bugzilla/valid-bug

#246 Add cleanup logging after tests run
  tests/e2e/framework/context.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#242 Add makefile targets to run serials and parallel e2e tests
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#243 Use fmt.Errorf instead of errors.New
  tests/e2e/helpers.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#244 Replace ioutils with io and os modules
  cmd/manager/resultcollector.go
  cmd/manager/resultcollector_test.go
  cmd/manager/resultserver.go
  cmd/manager/resultserver_test.go
  cmd/manager/scap.go
  cmd/manager/scap_test.go
  pkg/controller/common/constants.go
  pkg/utils/resultconfigmap.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/projutil.go
  tests/e2e/framework/resource.go
  tests/e2e/helpers.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#251 Use correct flag for e2e-parallel and e2e-serial
  Makefile
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#250 Refactor e2e test cleanup
  tests/e2e/framework/client.go
  tests/e2e/framework/common.go
  tests/e2e/framework/context.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/main_entry.go
  tests/e2e/framework/resource.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#253 Fix test log about --skip-cleanup-error
  tests/e2e/framework/context.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#261 Remove deprecated test context method
  tests/e2e/framework/resource.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#263 Add operator image workflow
  .github/workflows/release-latest.yml
  CHANGELOG.md
  bundle-latest.Dockerfile
  catalog.Dockerfile
  catalog/compliance-operator-catalog.json
Labels: approved

#267 Temporally change workflow dependency
  .github/workflows/release-latest.yml
  catalog/compliance-operator-catalog.json
Labels: approved

#268 Update catalog-container-push-latest workflow
  .github/workflows/release-latest.yml
  Makefile
  catalog.Dockerfile
  catalog/compliance-operator-catalog.json
Labels: approved

#262 rbac: Allow to Read imagepruners
  config/rbac/api_resource_collector_cluster_role.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#223 OCPBUGS-1803: Remove compliance_operator_compliance_scan_error_total …
  CHANGELOG.md
  doc/usage.md
  pkg/controller/metrics/metrics.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/valid-reference

#254 Simplify skipCleanupOnError test flag
  Makefile
  tests/e2e/framework/context.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/main_entry.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#235 Modify API Resource Collector to Convert YAML to JSON Format
  CHANGELOG.md
  cmd/manager/scap.go
  cmd/manager/scap_test.go
  tests/data/configmap_json.json
  tests/data/configmap_yaml.json
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#266 Fix formatting in projutil.go
  tests/e2e/framework/projutil.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#269 Fix trivial nits from PR 250
  tests/e2e/framework/main_entry.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#252 Add HyperShift usage doc
  CHANGELOG.md
  doc/usage.md
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#270 Add workflow for test content and must gather
  .github/workflows/must-gather-latest.yml
  .github/workflows/test-broken-content-latest.yml
Labels: approved, lgtm, bugzilla/valid-bug
