Repository ComplianceAsCode/compliance-operator, pull requests merged in 2024-04, with the labels that each got.

#494 CMP-2401: Add STIG reference parser
  pkg/profileparser/profileparser.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#503 OCPBUGS-32216: Stop deleting the kubeletconfiglink
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#504 Support disable profile bundle based on Arch
  cmd/manager/operator.go
Labels: approved, lgtm

#506 Fix a small typo
  pkg/utils/remediation_diff.go
Labels: approved, lgtm, ok-to-test

#493 Add test file needed for testing CaC content
  Makefile
  pkg/utils/parse_arf_result_test.go
Labels: approved, lgtm

#508 OCPBUGS-32797: updates the skipMetrics to include all platforms
  cmd/manager/operator.go
Labels: approved, lgtm, ok-to-test, qe-approved, jira/valid-bug, jira/valid-reference
