Repository ComplianceAsCode/compliance-operator, pull requests merged in 2024-01, with the labels that each got.

#429 [COMPLY-1339] add compare if image equals
  pkg/controller/compliancesuite/suitererunner_cron_compat.go
Labels: approved, lgtm, ok-to-test, qe-approved

#490 Fix e2e error
  tests/e2e/serial/main_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#488 Add GitHub action to build image on new PR
  .github/workflows/release-pr.yml
Labels: approved, qe-approved
