Repository ComplianceAsCode/compliance-operator, pull requests merged in 2024-08, with the labels that each got.

#565 Add yuumasato to owners file
  OWNERS
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#557 Update metrics navigation in documentation
  doc/usage.md
Labels: approved, lgtm

#558 CMP-2196: Update cluster role permissions for ingresscontrollers
  config/rbac/operator_cluster_role.yaml
Labels: approved, lgtm, jira/valid-reference

#566 :broom: Fix golang formatting in scan.go
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm

#574 OCPBUGS-37697: Remove newline in metrics doc literal
  doc/usage.md
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, jira/severity-low

#575 Add must-gather image builds to release on each push
  .github/workflows/release-latest.yml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#576 Fix must-gather base image
  images/must-gather/Dockerfile.ocp
Labels: approved, lgtm

#578 Remove multi-arch support from must-gather image
  .github/workflows/must-gather-latest.yml
  .github/workflows/release-latest.yml
Labels: approved, lgtm

#587 Add kubedeschedulers to api_resource_collector_clusterrole
  config/rbac/api_resource_collector_cluster_role.yaml
Labels: approved, lgtm, ok-to-test

#589 Add events to must-gather image
  utils/must-gather/gather_compliance
Labels: approved, lgtm

#592 Add commit-sha into pr image build
  .github/workflows/pr-image-trigger.yml
  .github/workflows/release-pr.yml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#594 Add PCI-DSS v4.0 reference parser
  pkg/profileparser/profileparser.go
Labels: approved, lgtm

#601 Update bundle manifests
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#593 Fix make bundle target
  Makefile
Labels: approved, lgtm, px-approved, docs-approved

#600 Fix GHA for bundle tests
  .github/workflows/bundle_tests.yaml
Labels: approved, lgtm

#602 Update bundle annotations to include must-gather image
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#608 Update bundle files
  bundle/manifests/compliance.openshift.io_compliancecheckresults.yaml
  bundle/manifests/compliance.openshift.io_complianceremediations.yaml
  bundle/manifests/compliance.openshift.io_compliancescans.yaml
  bundle/manifests/compliance.openshift.io_compliancesuites.yaml
  bundle/manifests/compliance.openshift.io_profilebundles.yaml
  bundle/manifests/compliance.openshift.io_profiles.yaml
  bundle/manifests/compliance.openshift.io_rules.yaml
  bundle/manifests/compliance.openshift.io_scansettingbindings.yaml
  bundle/manifests/compliance.openshift.io_scansettings.yaml
  bundle/manifests/compliance.openshift.io_tailoredprofiles.yaml
  bundle/manifests/compliance.openshift.io_variables.yaml
  config/crd/bases/compliance.openshift.io_compliancecheckresults.yaml
  config/crd/bases/compliance.openshift.io_complianceremediations.yaml
  config/crd/bases/compliance.openshift.io_compliancescans.yaml
  config/crd/bases/compliance.openshift.io_compliancesuites.yaml
  config/crd/bases/compliance.openshift.io_profilebundles.yaml
  config/crd/bases/compliance.openshift.io_profiles.yaml
  config/crd/bases/compliance.openshift.io_rules.yaml
  config/crd/bases/compliance.openshift.io_scansettingbindings.yaml
  config/crd/bases/compliance.openshift.io_scansettings.yaml
  config/crd/bases/compliance.openshift.io_tailoredprofiles.yaml
  config/crd/bases/compliance.openshift.io_variables.yaml
Labels: approved, lgtm

#609 fix: makefile had an incorrect phony
  Makefile
Labels: approved, lgtm, needs-ok-to-test

#591 CMP-2614: Implement update timestamps on ComplianceCheckResults
  cmd/manager/aggregator.go
  cmd/manager/common.go
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  tests/e2e/framework/common.go
  tests/e2e/parallel/main_test.go
Labels: approved, lgtm, qe-approved, px-approved, jira/valid-reference
