Repository ComplianceAsCode/compliance-operator, pull requests merged in 2024-06, with the labels that each got.

#530 Support Building multi-arch container imagers
  .github/workflows/release-latest.yml
  .github/workflows/release-pr.yml
  .github/workflows/release.yml
Labels: approved, lgtm

#532 Fix catalog image workflow
  .github/workflows/release-latest.yml
  .github/workflows/release-pr.yml
Labels: approved

#533 Skip failed unit tests for s390x
  .github/workflows/release-latest.yml
  .github/workflows/release-pr.yml
  cmd/manager/resultserver_test.go
Labels: approved, lgtm

#535 Fixing release image multi-arch support
  .github/workflows/release.yml
Labels: approved, lgtm

#536 Remove SBOM workaround
  .github/workflows/release-latest.yml
  .github/workflows/release-pr.yml
Labels: approved, lgtm

#537 OCPBUGS-17828: Fix rule instruction
  pkg/utils/parse_arf_result.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#497 OCPBUGS-19690: Enable host network to access host sysctls
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference
