Repository ComplianceAsCode/compliance-operator, pull requests merged in 2024-07, with the labels that each got.

#540 CMP-1096: Add must-gather image to relatedImages
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#541 Update must gather image workflow
  .github/workflows/must-gather-latest.yml
  .github/workflows/test-broken-content-latest.yml
Labels: approved, lgtm

#542 CMP-2688: Document using relatedImages for must-gather
  doc/usage.md
Labels: approved, lgtm, jira/valid-reference

#491 :broom: update golang to 1.21
  Dockerfile.ci
  Dockerfile.ocp
  cmd/manager/operator.go
  cmd/manager/operator_test.go
  go.mod
  go.sum
Labels: approved, lgtm, qe-approved

#548 Fix false positive trivy filesystem scan result
  .github/workflows/container-scan-trivy.yml
Labels: approved, lgtm

#547 Update TailoredProfile title description in parallel e2e
  tests/e2e/parallel/main_test.go
Labels: approved, lgtm

#546 Add Makefile target for pushing must-gather image
  Makefile
Labels: approved, lgtm, qe-approved

#553 :broom: update golang to 1.22
  Dockerfile.ci
  build/Dockerfile
  go.mod
  go.sum
Labels: approved, lgtm

#545 :broom: remove downstream-specific Dockerfile
  Dockerfile.ocp
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#556 Gather scan raw-results in must-gather image
  images/must-gather/Dockerfile.ocp
  utils/must-gather/fetch-raw-results-pod-template.yaml
  utils/must-gather/gather_compliance
Labels: approved, lgtm
