Repository ComplianceAsCode/compliance-operator, pull requests merged in 2024-05, with the labels that each got.

#509 OCPBUGS-33067: Don't fatal error when filter cannot iterate
  cmd/manager/scap.go
  cmd/manager/scap_test.go
  tests/data/empty_machineconfig.json
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#516 Fix platform role detection for Power and Z architecture
  cmd/manager/operator.go
Labels: approved, lgtm

#515 CMP-2547: Implement ROSA e2e test suite
  Makefile
  tests/e2e/framework/common.go
  tests/e2e/framework/framework.go
  tests/e2e/rosa/main_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#502 Add unique profile ID
  cmd/manager/aggregator.go
  cmd/manager/operator.go
  pkg/apis/compliance/v1alpha1/profile_types.go
  pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/nodeutils.go
  pkg/xccdf/tailoring.go
  tests/e2e/framework/common.go
  tests/e2e/serial/main_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#518 CMP-2524: Only load node profiles for managed OpenShift
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  cmd/manager/operator.go
  config/rbac/operator_cluster_role.yaml
  go.mod
  go.sum
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/profilebundle/profilebundle_controller.go
  pkg/profileparser/profileparser.go
  pkg/utils/platform.go
  tests/e2e/rosa/main_test.go
  vendor/modules.txt
  vendor/open-cluster-management.io/api/LICENSE
  vendor/open-cluster-management.io/api/cluster/v1/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1/doc.go
  vendor/open-cluster-management.io/api/cluster/v1/register.go
  vendor/open-cluster-management.io/api/cluster/v1/types.go
  vendor/open-cluster-management.io/api/cluster/v1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1/zz_generated.swagger_doc_generated.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0000_02_clusters.open-cluster-management.io_clusterclaims.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/0000_05_clusters.open-cluster-management.io_addonplacementscores.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1alpha1/doc.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/helpers.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/register.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/types.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/types_addonplacementscore.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/types_rolloutstrategy.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/0000_02_clusters.open-cluster-management.io_placements.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta1/0000_03_clusters.open-cluster-management.io_placementdecisions.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta1/doc.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/helpers.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/register.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/types_placement.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/types_placementdecision.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, jira/valid-reference

#520 CMP-2526: Disable automatic remediation for ROSA HCP environments
  cmd/manager/operator.go
  tests/e2e/framework/common.go
  tests/e2e/rosa/main_test.go
Labels: approved, lgtm, jira/valid-reference

#521 Fix panic due to logging issue
  pkg/profileparser/profileparser.go
Labels: approved, lgtm

#522 Reduce timeout from 30 minutes to 10 minutes in serial tests
  tests/e2e/serial/main_test.go
Labels: approved, lgtm

#499 Release v1.4.1
  CHANGELOG.md
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  catalog/preamble.json
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#500 Use git describe for finding operator version
  Makefile
  utils/get-current-version.sh
Labels: approved, lgtm, qe-approved

#525 OCPBUGS-34535: Ignore case when compare platform
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  cmd/manager/operator.go
  config/rbac/operator_cluster_role.yaml
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/profilebundle/profilebundle_controller.go
  pkg/profileparser/profileparser.go
  pkg/utils/platform.go
  tests/e2e/framework/common.go
  tests/e2e/rosa/main_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, jira/severity-low
