Repository ComplianceAsCode/compliance-operator, pull requests merged in 2025-03, with the labels that each got.

#704 CMP-3149: Add content with a deprecated profile
  .github/workflows/test-broken-content-latest.yml
  images/testcontent/broken-content.sh
  images/testcontent/deprecated_profile/ssg-ocp4-ds.xml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#701 CMP-3155: Fix e2e test for checkcount
  tests/e2e/framework/common.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#610 Add BSI reference parser
  pkg/profileparser/profileparser.go
Labels: approved, lgtm, qe-approved

#690 CMP-3149: Handle profile deprecation
  pkg/apis/compliance/v1alpha1/profilebundle_types.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/profileparser/profileparser.go
  pkg/xccdf/tailoring.go
  tests/e2e/framework/common.go
  tests/e2e/parallel/main_test.go
  tests/e2e/serial/main_test.go
Labels: approved, lgtm, jira/valid-reference
