Repository ComplianceAsCode/compliance-operator, pull requests merged in 2025-07, with the labels that each got.

#731 CMP-3138: Only build broken test content on master
  .github/workflows/test-broken-content-latest.yml
Labels: approved, lgtm, jira/valid-reference

#729 Release v1.7.1
  CHANGELOG.md
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  catalog/preamble.json
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  images/must-gather/Containerfile
  images/openscap/Containerfile
  images/operator/Dockerfile
  version.Makefile
  version/version.go
Labels: approved

#732 Build images for arm64 in Konflux
  .tekton/compliance-operator-dev-pull-request.yaml
  .tekton/compliance-operator-dev-push.yaml
  .tekton/compliance-operator-must-gather-dev-pull-request.yaml
  .tekton/compliance-operator-must-gather-dev-push.yaml
  .tekton/compliance-operator-openscap-dev-pull-request.yaml
  .tekton/compliance-operator-openscap-dev-push.yaml
Labels: approved, lgtm

#739 Add required labels for release
  images/must-gather/Containerfile
  images/openscap/Containerfile
  images/operator/Dockerfile
Labels: approved, lgtm

#737 Fix pipelines target branch to release-1.7
  .tekton/compliance-operator-bundle-release-1-7-pull-request.yaml
  .tekton/compliance-operator-bundle-release-1-7-push.yaml
  .tekton/compliance-operator-must-gather-release-1-7-pull-request.yaml
  .tekton/compliance-operator-must-gather-release-1-7-push.yaml
  .tekton/compliance-operator-openscap-release-1-7-pull-request.yaml
  .tekton/compliance-operator-openscap-release-1-7-push.yaml
  .tekton/compliance-operator-release-1-7-push.yaml
  .tekton/compliance-operator-release-pull-request.yaml
Labels: approved, lgtm

#741 CMP-3340: Add required labels for release
  images/must-gather/Containerfile
  images/openscap/Containerfile
  images/operator/Dockerfile
Labels: approved, lgtm, jira/valid-reference
