Repository ComplianceAsCode/compliance-operator, pull requests merged in 2025-02, with the labels that each got.

#661 bump co version 1.6.2 dev
  Makefile
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  catalog/preamble.json
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  version.Makefile
Labels: approved, lgtm

#676 Build test content using arm64
  .github/workflows/test-broken-content-latest.yml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#677 Run test-broken-content-latest action when updated
  .github/workflows/test-broken-content-latest.yml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#618 add read permission for kataconfig
  bundle/manifests/compliance-operator.clusterserviceversion.yaml
  config/manifests/bases/compliance-operator.clusterserviceversion.yaml
  config/rbac/api_resource_collector_cluster_role.yaml
Labels: approved, lgtm, ok-to-test, qe-approved, px-approved, docs-approved

#680 Fix Release Image Action
  .github/workflows/release-pr.yml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#679 Update release actions to build images for ARM64
  .github/workflows/release-latest.yml
  .github/workflows/release.yml
Labels: approved, lgtm

#687 Revert arm64 support for must-gather image
  .github/workflows/release-latest.yml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#689 OCPBUGS-48461: enhance error handling for PrometheusMetricTargets
  tests/e2e/framework/utils.go
  tests/e2e/parallel/main_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/valid-reference

#691 CMP-3152: Implement an action to check PR titles
  .github/workflows/check-pr-title.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#685 OCPBUGS-51267: Fix an issue in the ComplianceScan controller
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/severity-moderate, jira/valid-reference

#688 CMP-3121: Increase unit test timeout to 20 minutes
  Makefile
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference
